# Generated by Django 5.2.6 on 2025-09-08 10:58

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField(help_text='Enter 6-digit pin code', validators=[student.models.validate_pin_length])),
                ('state', models.CharField(choices=[('Assam', 'Assam'), ('Bihar', 'Bihar'), ('mp', 'mp'), ('gujarat', 'gujarat'), ('delhi', 'delhi')], max_length=100)),
                ('mobile', models.CharField(help_text='Enter a 10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.ImageField(blank=True, upload_to='doc')),
            ],
        ),
    ]
